const mongoose=require("mongoose")
const cors=require("cors")
const express=require("express")
const dotenv=require('dotenv')
const userRouter=require('./routes/userRoutes')
const categoryRouter=require('./routes/categoryRoutes')
const productRouter=require('./routes/productRouter')
const app=express()
const configureDB=require('./configureDB/db')
require('dotenv').config();
PORT=process.env.PORT
app.use(express.json())
app.use(cors())
dotenv.config()
configureDB()
app.use('/user',userRouter)
app.use('/category',categoryRouter)
app.use('/product',productRouter)
app.listen(PORT,()=>{
    console.log("server running on port",PORT)
})